### ISSUE TITLE
how can add speaker into my transcription with IBM

### ISSUE THREAD

**Issue by johnfelipe** [OpenNewsLabs/autoEdit_2#100]
![SNAG-0214](https://user-images.githubusercontent.com/428820/104061637-f8887900-51c6-11eb-93a5-8848df04cb96.png)

red one is women
green one is men

how add speaker name of men?

**Comment by pietrop** [comment]
👋 in autoEdit2 it's not possible. but it is possible in [autoEdit 3](https://www.autoedit.io/) by pressing enter.

**Comment by johnfelipe** [comment]
How much time por version 3 for have spanish broadband ibm stt?

**Comment by pietrop** [comment]
https://github.com/pietrop/digital-paper-edit-electron/issues/51#issuecomment-756998337
