### ISSUE TITLE
wich is size max for upload for watson

### ISSUE THREAD

**Issue by johnfelipe** [OpenNewsLabs/autoEdit_2#101]
i have 195 mb mp3 audio file and upload with watson credentials but i see is not working:

![SNAG-0286](https://user-images.githubusercontent.com/428820/109336214-15d5dd00-7831-11eb-8f4d-1eca00a672db.png)

is a max size file parameter?

**Comment by pietrop** [comment]
I think it's in their docs, last I checked ( a few years ago) I think It should be 100mb (❓)

However autoEdit2 also converts it into a audio that meets the STT audio specs. 

if you are on a mac and you replace `{YOUR USER'S HOME FOLDER NAME}` with your user's home folder below
```
/Users/{YOUR USER'S HOME FOLDER NAME}/Library/Application\ Support/autoEdit2
```

You can use this in Mac OSX Finder's navbar under `Go` -> `Go To Folder`

in there there should be a media folder, where you should see the converted audio, and you can check the file size. It should be a `.ogg` file.

What's the duration of your `.mp3`?

**Comment by johnfelipe** [comment]
What's the duration of your .mp3?

183 mb

then i upload only less 100 mb size
Tnks
