### ISSUE TITLE
Search field doesn't highlight/return results

### ISSUE THREAD

**Issue by nanseay** [OpenNewsLabs/autoEdit_2#11]
There is a Search field on the Transcription Show page, currently the field does not return any results if a user adds text to the field.

1) Open autoEdit 2 app
2) Add file to have access to transcript or open an existing transcript
3) On transcript show page, enter text in the Search field

Expected: Entered text that matches text in the transcription should be highlighted
Actual: No text is highlighted, error message 'Uncaught ReferenceError: searchTextArray is not defined`
![search field](https://cloud.githubusercontent.com/assets/11615553/21061760/b29e0506-be1b-11e6-9009-b01c265abee3.gif)

**Comment by pietrop** [comment]
Figured it out, the variable [`searchTextArray`](https://github.com/OpenNewsLabs/autoEdit_2/blob/master/lib/app/views/transcription_view.js#L540) in `lib/app/views/transcription_view.js` was not initialised with `var`  and under strict mode it was causing the error.  Will update in next release `1.0.6`.
