### ISSUE TITLE
Clear highlights does not persist when navigating away and returning

### ISSUE THREAD

**Issue by jhdouglas** [OpenNewsLabs/autoEdit_2#12]
A Clear highlights option allows users to remove all selected text within a transcript. If a user clears all highlights via this button then navigates away from the transcript and returns, the changes do not persist.

1) Open autoEdit 2 app
2) Add file to have access to transcript
3) Open transcript show page
4) Highlight sections of text
5) Use Clear highlights option
6) Observe highlights are cleared
7) Navigate away from transcript and return
8) Note highlighted sections are back

![clear_highlights](https://cloud.githubusercontent.com/assets/5640831/21062175/9d45a928-be1d-11e6-9938-b2c36ba2e809.gif)

**Comment by pietrop** [comment]
fixed and tested.
