### ISSUE TITLE
Edit text in popup when canceling `Clear highlights`

### ISSUE THREAD

**Issue by jhdouglas** [OpenNewsLabs/autoEdit_2#13]
A confirmation popup displays when attempting to clear highlights where the user can either cancel or proceed. If the user cancels, the associated popup does not make sense. It reads, “relax, nothing was cancelled.”

It appears it should read “relax, nothing was cleared.” or something similar.

1) Open autoEdit 2 app
2) Add file to have access to transcript
3) Open transcript show page
4) Highlight sections of text and use Clear highlights option
5) Press cancel
6) Observe popup
7) Note text

<img width="438" alt="screenshot 2016-12-09 14 42 41" src="https://cloud.githubusercontent.com/assets/5640831/21062401/bca08c42-be1e-11e6-836f-66b28ec80e6d.png">

**Comment by pietrop** [comment]
Making a note that "relax" should also be capitalised.

**Comment by pietrop** [comment]
I've fixed it for version `1.0.6`.
