### ISSUE TITLE
Unable to pause video while editing text

### ISSUE THREAD

**Issue by jhdouglas** [OpenNewsLabs/autoEdit_2#14]
Users have the ability to edit specific words in the transcription text via edit mode. However, upon clicking on a word to edit, the video autoplays by default. This means that users can never pause the video to edit text and it continually plays in the background. 

It seems that in edit mode, autoplay of video when single clicking text should be disabled or users should be able to control if the video is played or not when editing.

1) Open autoEdit 2 app
2) Add file to have access to transcript
3) Open transcript show page
4) Enable edit mode
5) Click on word in transcript
6) Observe video autoplays
7) Note video cannot be paused while editing words

<img width="1033" alt="screenshot 2016-12-09 15 13 19" src="https://cloud.githubusercontent.com/assets/5640831/21063214/72376f82-be22-11e6-800c-0d1a255213ca.png">

**Comment by pietrop** [comment]
closing in favour of #39
