### ISSUE TITLE
Using `cmd + a` in edit mode does not select word

### ISSUE THREAD

**Issue by jhdouglas** [OpenNewsLabs/autoEdit_2#15]
When entering edit mode a notification displays at the top of the page with instructions. It reads “Click on a word to edit. Use cmd + a to select a word. Tab or click to move to the next word.” However, using cmd + a in edit mode doesn’t appear to do anything. Clicking a word automatically allows users to edit. It may be beneficial to remove `cmd` + `a` from the instructions.

1) Open autoEdit 2 app
2) Add file to have access to transcript
3) Open transcript show page
4) Enable edit mode
5) Observe instructions
6) Attempt to use `cmd` + `a` to select a word
7) Note clicking word allows it to be edited and `cmd` + `a` does nothing

<img width="956" alt="screenshot 2016-12-09 15 30 09" src="https://cloud.githubusercontent.com/assets/5640831/21063720/1cf5cdd6-be25-11e6-8eaf-e7a8ee3643e6.png">

**Comment by pietrop** [comment]
The text  `cmd` + `a` description is now redundant, as it should automatically select the text of a word when clicking on it. Removing in version `1.0.6`

**Comment by pietrop** [comment]
I've replaced it with `Click on a word to edit. Tab or click to move to the next word.`

**Comment by pietrop** [comment]
I've fixed it for version `1.0.6`.
