### ISSUE TITLE
Typo in popup when clearing highlights from transcript

### ISSUE THREAD

**Issue by jhdouglas** [OpenNewsLabs/autoEdit_2#19]
A confirmation popup displays when attempting to clear highlights where the user can either cancel or proceed. There is currently a minor typo in this text where “highlights” should be changed to “highlighted” for better readability.

Current: “...clear all of the **highlights** sections from this transcript.” 
Edited: “...clear all of the **highlighted** selections from this transcript.”

1) Open autoEdit 2 app
2) Add file to have access to transcript
3) Open transcript show page
4) Highlight sections of text and use Clear highlights option
5) Observe popup displays
6) Note typo “highlights” instead of “highlighted”

![screenshot 2016-12-12 11 21 19](https://cloud.githubusercontent.com/assets/5640831/21107137/b0a4ae0e-c05e-11e6-8a91-4052b7df395d.png)

**Comment by pietrop** [comment]
I've fixed it for version `1.0.6`.
