### ISSUE TITLE
'?' in export menu should direct users to section (3) of user manual

### ISSUE THREAD

**Issue by jhdouglas** [OpenNewsLabs/autoEdit_2#20]
A `?` is included in the video sequence portion of the export menu. It currently directs users to section **(4) Reconnect in video editing software of choice** of the manual. However, because of its location in the export modal, it seems that it would make sense and give users more context to direct to the previous section in the user manual, **(3) Exporting a video sequence (EDL)**. 

1) Open autoEdit 2 app
2) Open any transcript
3) Click Export to open menu
4) Click `?` in video sequence section
5) Observe users taken to (4) of user manual (http://www.autoedit.io/user_manual/usage.html#reconnect-in-video-editing-software-of-choice)
6) Note being directed to (3) might make more sense

![help_text_export](https://cloud.githubusercontent.com/assets/5640831/21109297/6befe352-c066-11e6-8de2-0516d29db63d.gif)

**Comment by pietrop** [comment]
Changed the link to [https://opennewslabs.github.io/autoEdit_2/user_manual/usage.html#exporting-a-video-sequenceedl](https://opennewslabs.github.io/autoEdit_2/user_manual/usage.html#exporting-a-video-sequenceedl)

I've fixed it for version `1.0.6`.
