### ISSUE TITLE
Increase size of video player, controls

### ISSUE THREAD

**Issue by jhdouglas** [OpenNewsLabs/autoEdit_2#21]
When viewing a transcript the associated video displays on the left side of the screen next to the text. The video player is currently very small, which makes it difficult to track through the video, adjust volume, etc., with accuracy. Additionally, the fullscreen button is cut off.

While there are other methods to navigate through the transcript and adjust volume (clicking text in transcript, using shortcuts), it may be beneficial to increase the player size so users can successfully and accurately control the video.

1) Open autoEdit 2 app
2) Add file to have access to transcript
3) Open transcript show page
4) Observe video on left side of screen
5) Note size of player, controls and difficulty in using

![screenshot 2016-12-12 13 22 39](https://cloud.githubusercontent.com/assets/5640831/21111228/7f45f696-c06e-11e6-8985-23a2aba5b4af.png)

**Comment by pietrop** [comment]
closing for now, but welcome suggestions on how to fix this.
