### ISSUE TITLE
Add ability to sort transcripts on the dash (via Title, Date)

### ISSUE THREAD

**Issue by jhdouglas** [OpenNewsLabs/autoEdit_2#22]
The transcriptions dashboard is a list of all processed transcripts. Currently, there is no way to sort these files. This could pose problems if there are a multitude of uploaded transcripts, as the user would have to scroll through all files to locate the desired transcript. For convenience, it would be nice to be able to sort these, possibly via Title and/or Date.

1) Open autoEdit 2 app
2) Upload several files and allow them to process
3) Return to dashboard
4) Observe no way to sort uploaded transcripts

<img width="801" alt="screenshot 2016-12-12 13 48 58" src="https://cloud.githubusercontent.com/assets/5640831/21112091/62a20c38-c072-11e6-8d6e-904688461b76.png">

**Comment by pietrop** [comment]
Closing this for now, as will revisit when adding projects to group transcripts and paperedits together
