### ISSUE TITLE
Export menu incorrectly lists 'JSON EDL Chronological' option twice

### ISSUE THREAD

**Issue by jhdouglas** [OpenNewsLabs/autoEdit_2#23]
Users have the ability to export a JSON version of the transcript in either EDL Chronological or EDL Selection Order. Currently, EDL Chronological is listed twice in this section. One option should list EDL Selection Order per its description.

1) Open autoEdit 2 app
2) Add file to have access to transcript
3) Open transcript show page
4) Click Export to view options
5) Observe JSON section
6) Note duplicate EDL Chronological options

<img width="597" alt="screenshot 2016-12-12 14 54 52" src="https://cloud.githubusercontent.com/assets/5640831/21114785/46f72fd6-c07c-11e6-942d-c58c54d9aa00.png">

**Comment by pietrop** [comment]
I've fixed it for version `1.0.6`

**Comment by pietrop** [comment]
Needs looking into if the output of the two json is what expected (chronological vs selection order) before moving to "Needs Review" label.

**Comment by pietrop** [comment]
In transcription `Recodes Peter Kafka interviews Turner CEO John Martin Wednesday Nov. 30 7pm ET.mp3` selected first starting at `00:00:05:17`

>because even waking up on election day I would bet that Hillary would want and I actually thought Hillary were won by a considerable margin that was conventional wisdom 

then second starting at `00:01:32:13`

>the pepper it up there at the end thanks for coming %HESITATION thanks Rick talked late August early September you show me your tattoos I'm hoping that you'll be doing that at some point maybe as a 

When looking at the EDL text selection and EDL json files noticed that they are the same. Both appear in chronological order.

![screen shot 2016-12-13 at 14 28 17](https://cloud.githubusercontent.com/assets/4661975/21155513/6c99cf90-c140-11e6-8023-48709faa990e.png)

![screen shot 2016-12-13 at 14 33 48](https://cloud.githubusercontent.com/assets/4661975/21155716/3a5634f0-c141-11e6-9f07-392f88656ea8.png)
