### ISSUE TITLE
EDL file verification 2 (Chronological order)

### ISSUE THREAD

**Issue by SteveLeon2** [OpenNewsLabs/autoEdit_2#27]
EDL file verification 2 (Chronological order)
Below are the details and files needed for EDL testing via video editing software.

Video: norman_door.mp4 -- one of the test files you sent QA

Selected text: [Norm_long_TTEDLC_13_12_2016_15-19-05.txt](https://github.com/OpenNewsLabs/autoEdit_2/files/650238/Norm_long_TTEDLC_13_12_2016_15-19-05.txt)

![screenshot 2016-12-13 15 30 19](https://cloud.githubusercontent.com/assets/23086118/21160574/5a5b32d4-c153-11e6-8da3-10d27ca94a25.png)

EDL file: [Norm_long_chronologicalEDLCO_13_12_2016_15-18-41.edl.zip](https://github.com/OpenNewsLabs/autoEdit_2/files/650239/Norm_long_chronologicalEDLCO_13_12_2016_15-18-41.edl.zip)

**Comment by jhdouglas** [comment]
Pietro, here's another EDL file from a different video to verify.
