### ISSUE TITLE
Highlighting a line where another line in close proximity has similar text will highlight both lines

### ISSUE THREAD

**Issue by nanseay** [OpenNewsLabs/autoEdit_2#30]
1) Open autoEdit 2 app
2) Add file to have access to transcript (e.g. JesselynRadackonVimeo.mp4)
3) Open transcript show page
4) Highlight sections of text (e.g. `i found that`)

Expected: only the selected text is highlighted
Actual: text above selected text is also highlighted, unselecting unintended highlighted text will remove highlight from both lines
![highlight weirdness](https://cloud.githubusercontent.com/assets/11615553/21192742/96d9d4e6-c1f7-11e6-97e6-3c4686fb36db.gif)

**Comment by pietrop** [comment]
Was this with IBM or Gentle transcription?

**Comment by nanseay** [comment]
@pietrop Gentle transcription

**Comment by pietrop** [comment]
ok, thanks, that's what I suspected

**Comment by pietrop** [comment]
I think the issue with Gentle word time-codes might have been that they overlap. 
Closing this issue for now as Gentle is more of a bonus feature, however if anyone else experience this again and would like to get it addressed, feel free to re-open.
