### ISSUE TITLE
Text edited in autoEdit2 does not persist in exported files

### ISSUE THREAD

**Issue by nanseay** [OpenNewsLabs/autoEdit_2#31]
1) Open autoEdit 2 app
2) Add file to have access to transcript (e.g. norman_door.mp4 using Gentle)
3) Open transcript show page
4) Click Edit
5) Select a word to edit (e.g. changed fox to vox)
6) Click Export button

autoEdit2 app
<img width="801" alt="edited transcription" src="https://cloud.githubusercontent.com/assets/11615553/21196656/70b45ce6-c206-11e6-8f1c-6d72d97ee7c7.png">

Expected: exported file should display edited transcription
Actual: exported file still has original transcription
Plain text selection: [Norman_Gentle_EDL_14_12_2016_13-55-05.txt](https://github.com/OpenNewsLabs/autoEdit_2/files/652604/Norman_Gentle_EDL_14_12_2016_13-55-05.txt)
![exported selections](https://cloud.githubusercontent.com/assets/11615553/21196975/be2fa7a4-c207-11e6-9280-38b357a11b02.png)

**Comment by pietrop** [comment]
This is for Gentle only or IBM As well?

**Comment by pietrop** [comment]
Works with IBM so closing for now. As `gentle` is a bit more experimental and needs more looking into it.
