### ISSUE TITLE
Add "full" to plain text description section for clarity

### ISSUE THREAD

**Issue by jhdouglas** [OpenNewsLabs/autoEdit_2#32]
Users have the ability to export full transcripts via the `Plain text transcription` and `Timecoded plain text transcription` options. It may be beneficial to add “full” to the Plain text transcription description (as in the Timecoded option) for further clarity to users.

“You can export the text of the **full** transcription as plain text without timecodes.”

1) Open autoEdit 2 app
2) Add file to have access to transcript
3) Open transcript show page
4) Click Export to view options
5) Observe description for Plain text transcription
6) Note “full” missing from description

<img width="599" alt="screenshot 2016-12-14 14 26 38" src="https://cloud.githubusercontent.com/assets/5640831/21197489/a98bd0d2-c209-11e6-8646-e4fdef761158.png">

**Comment by pietrop** [comment]
fixed for version 1.0.6.
