### ISSUE TITLE
No way to change IBM credentials

### ISSUE THREAD

**Issue by kristinalustig** [OpenNewsLabs/autoEdit_2#35]
If a user enters incorrect or invalid IBM credentials there is no way to remove them and enter updated credentials - even after deleting and reinstalling the mac app.

**Comment by pietrop** [comment]
Hi @kristinalustig, 
Yes, that's a good point, and something I am planning to address. Perhaps by adding a settings panel, where the user can review the credentials. 

Here's a bit of an update of where I am at with this. 

At the moment, if you uninstall using app cleaner, as [described in the user manual](http://www.autoedit.io/user_manual/uninstalling.html) when re-installing again it will prompt you to add the credentials again. As app cleaner does a clean uninstall. while just dragging the icon into the trash leaves all the system preferences on the computer (including the API credentials). 

--- 

This is a bit of a hack, but to review credentials, they are stored inside 

`/Users/{{you username for the home folder}}/Library/Application Support/autoEdit2/wttskeys.json`

To get to that file: 

- click on the finder
- in the top bar click on `Go`
- in the menu select ` Go To Folder...`
- Then paste this  `/Users/{{you username for the home folder}}/Library/Application Support/autoEdit2`.  replacing `{{you username for the home folder}}` with the name of your computer's home folder. 
- there you'll find `wttskeys.json`
- open with [Sublime text](https://www.sublimetext.com) or equivalent text editor to review. (make sure you don't open with text edit if in rich text mode).

--- 

However I'd normally just recommend to uninstall and try again. I am also working on adding some better Error handling to signal the issue when a user puts incorrect credentials and IBM watson returns an error.

**Comment by pietrop** [comment]
[connected with this issue](https://github.com/OpenNewsLabs/autoEdit_2/issues/4)

**Comment by pietrop** [comment]
Added error handing when user puts wrong/incorrect credentials for IBM Watson stt. This will be updated in next release in version `1.0.6`

![screen shot 2017-04-28 at 00 34 55](https://cloud.githubusercontent.com/assets/4661975/25507738/3f56a0ac-2bae-11e7-97db-49008fbebe7d.png)

For clarities purposes, and in case anyone has better suggestions on how to best implement this,  Here is an overview of the implementation. 

Modified these modules responsible for generating an saving the transcription 

- `/autoEdit_v2/lib/interactive_transcription_generator/transcriber/ibm_stt_node/send_to_watson.js`
- `/autoEdit_v2/lib/interactive_transcription_generator/transcriber/index.js`
- `/autoEdit_v2/lib/interactive_transcription_generator/index.js`
- `/autoEdit_v2/nwjs/db.js`

- and added `error` as first param of callback, which is set as `null` if successful. 

- Then in transcription model added `error` attribute. To store error object to display the info to the user. 

- used `model.set()` to update model with the error.
- also added `status: null` to the transcription to signify there has been an error. 
  - This means that there are 3 options for `staus`:
    -  `true` == sucesfully complete everything, 
    - `false` == still being processed, corresponds to wheel spinning, 
    - `null` == when error occurs with IBM API. 

- then in template view added an if else, and if it's `null` display error message. 
with some extra text in yellow to allow with troubleshooting. 
- also change bin to error triangle and remove disable. 
- but kept disable on in processed spinning icon for transcription.  

More error handling coverage is needed across the app but this is a start.

**Comment by pietrop** [comment]
Closing for now. Going to deal with allowing user to edit/change credentials with a settings panel at a later stage as a separate issue.
