### ISSUE TITLE
Unauthorized when using IBM Watson from non-UK region

### ISSUE THREAD

**Issue by sedubois** [OpenNewsLabs/autoEdit_2#38]
As the title says, I tried Watson for the first time and set it up in the Germany region, but then the watson subdomain needs to be suffixed with `-fra` (Frankfurt, I guess), which autoEdit2 doesn't take into account and just throws an unauthorized error.

Would be great to either be flexible on the region or at least give a tip that the UK region is required.

**Comment by pietrop** [comment]
Thanks for flagging this @sedubois. 

If I understand this right, when you get the credentials from Watson, it gives you a URL, username and password. Are you saying the URL you get if you chose Germany as a region is not `https://stream.watsonplatform.net/speech-to-text/api` but is something else? with a region prefix?


In autoEdit, I used the  [`watson-developer-cloud`, `speech_to_text`](https://github.com/watson-developer-cloud/node-sdk#speech-to-text) to communicate with Watson. 
And as you can see [here in their code](https://github.com/watson-developer-cloud/node-sdk/blob/master/speech-to-text/v1.js#L91) they hard coded the url in. If this is the problem it be good to raise an issue on their repo, linking to this issue if needed as an example use case, and then once they fixed it I can update it in autoEdit by passing the url as an optional parameter, and adding it to the settings panel as well. 

Let me know if that makes sense, and if you think that, it might be the problem or not.

**Comment by sedubois** [comment]
@pietrop yes, the URL for Germany was different, it was something like https://stream-fra.watsonplatform.net. It looks indeed like their lib should take the region into account, but I'm really not familiar with this API besides what I wrote here.

**Comment by pietrop** [comment]
Apologies for the delay, did you managed to get it working?

Closing unless you need further help on this, in which case can re-open.

**Comment by sedubois** [comment]
Thanks, I workarounded this by just using the region that autoEdit2 was happy with.
