### ISSUE TITLE
Suggest IBM Auth check

### ISSUE THREAD

**Issue by learning-more** [OpenNewsLabs/autoEdit_2#4]
Hi Peitro, amazing project! 

Small tip: If other users encounter a spinning icon that doesn't stop in autoEdit 2's transcriptions window, it could be related the to incorrect IBM username / password. IBM Bluemix's website lists the password FIRST before the username. 

I uninstalled as you recommended, reinstalled, input the IBM username / password and my video processed shortly.

**Comment by pietrop** [comment]
Yes, that's a good point, I am thinking of adding some error handling system both at the level of the node module handling the Watson request as well as feedback through the app to make it easier to deal with it if that happens.

**Comment by pietrop** [comment]
connect with issue #35

**Comment by pietrop** [comment]
closed as resolved in  #35
