### ISSUE TITLE
Cannot export SRT second time

### ISSUE THREAD

**Issue by sedubois** [OpenNewsLabs/autoEdit_2#47]
After exporting SRT subtitles a first time with Transcriptions > Export > Captions, the button doesn't do anything anymore when trying to export a second time. The same behavior does not occur e.g when exporting EDLs. I don't know any workaround. Using macOS 1.0.10.

**Comment by sedubois** [comment]
Thanks @pietrop, as indicated I'm on macOS using autoEdit2 version 1.0.10. What does Cmd+alt+j means on a mac keyboard? I tried option-cmd-j and ctrl-cmd-j to no avail.

Also the subtitlesComposer-app looks really promising, but after installing it + the aneneas aligner, I didn't get it working: after clicking "create subtitle" it keeps showing "processing..." even after 10 minutes. Is there some debug console to look at?

Extra notes about subtitlesComposer:
- it seems the configuration "Number of lines per screen" (which has a default value of 2) can't be changed.
- the [documentation](https://pietropassarelli.gitbooks.io/subtitlecomposer-app/content/) says the latest version is 1.0.2 but on GitHub there's only 1.0.1 available.

**Comment by pietrop** [comment]
@sedubois sorry, it's `Cmd`+`alt`+**`i`** to open the console in autoEdit (same command as to open the inspector in chrome)

if you can replicate the error, and upload a screenshot here, of the error logs in the console, I can get a better sense of what's causing the issue. 

re-subtitlesComposer 
- going to test it out to double check.
- The configuration is fixed at 2 lines per "screen" as that's a lot more involved as a setting to adjust.
- checking if I need to upload an updated `1.0.2` version of it's just a number mistake.

**Comment by sedubois** [comment]
OK great, that works. Here's the stack trace:
```js
Uncaught TypeError: Cannot read property 'startTime' of undefined
    at file:///Applications/autoEdit2.app/Contents/Resources/app/electron/app.js:477:68
    at Array.forEach (native)
    at file:///Applications/autoEdit2.app/Contents/Resources/app/electron/app.js:458:30
    at Array.forEach (native)
    at loopThroughStuff (file:///Applications/autoEdit2.app/Contents/Resources/app/electron/app.js:457:12)
    at Function.returnSrtContent (file:///Applications/autoEdit2.app/Contents/Resources/app/electron/app.js:491:5)
    at child.expoertCaptionsSrt (file:///Applications/autoEdit2.app/Contents/Resources/app/electron/app.js:2871:49)
    at HTMLDivElement.dispatch (file:///Applications/autoEdit2.app/Contents/Resources/app/electron/app.js:13396:27)
    at HTMLDivElement.elemData.handle (file:///Applications/autoEdit2.app/Contents/Resources/app/electron/app.js:13048:28)
```

**Comment by pietrop** [comment]
Thanks for the error log, 
 
re-subtitle composer, I've added a new version, which I tested locally and seemed to work fine, see if it works for you. 

https://github.com/pietrop/subtitlesComposer-app/releases/tag/1.0.2

Not quiet sure what it's causing that error, need more time to look into it..

**Comment by pietrop** [comment]
@sedubois do you still have this issue with exporting `srt`?
I couldn't reproduce the issue in autoEdit...

**Comment by sedubois** [comment]
@pietrop I checked and still have it with my autoEdit2 1.0.10 on mac. I open a transcription, click export > Captions - srt --> it works I get the file saving popup. I cancel, then click the Captions - srt button again then get the error shown above (https://github.com/OpenNewsLabs/autoEdit_2/issues/47#issuecomment-390467057).

**Comment by pietrop** [comment]
Just tested on `1.0.16` and was able to export caption twice in a row, but feel free to reopen if you are still experience this issue in the latest version.
