### ISSUE TITLE
WebVTT support

### ISSUE THREAD

**Issue by sedubois** [OpenNewsLabs/autoEdit_2#48]
Vimeo recommends WebVTT as subtitle format, so it would be nice if autoEdit2 could export in this format instead or additionally to SRT.

**Comment by pietrop** [comment]
For now, I'd say `subtitlesComposer-app`can export as `vtt` see the update in this issue 
 https://github.com/OpenNewsLabs/autoEdit_2/issues/47

**Comment by sedubois** [comment]
Great, thanks. I will close this.
