### ISSUE TITLE
Typo in highlight mode notification

### ISSUE THREAD

**Issue by jhdouglas** [OpenNewsLabs/autoEdit_2#6]
When on the transcript show page, a notification displays above the transcript letting the user know which mode is being used -- highlight or edit. Currently, there is a typo when in highlight mode. 

It reads “You are in `hilight` mode.” In this instance `hilight` should be changed to `highlight`.

1) Open autoEdit 2 app
2) Add file to have access to transcript
3) Open transcript show page
4) Ensure highlight mode is active
5) Observe notification at top of page
6) Note typo of “hilight”

<img width="737" alt="screenshot 2016-12-09 11 24 39" src="https://cloud.githubusercontent.com/assets/5640831/21056298/0080ad46-be03-11e6-8300-cd577c21c10e.png">

**Comment by pietrop** [comment]
I've fixed it for version `1.0.6`.
