### ISSUE TITLE
Long strings of text can extend past borders in file info dropdown

### ISSUE THREAD

**Issue by jhdouglas** [OpenNewsLabs/autoEdit_2#7]
On the transcript show page users can access info about the specific file. Currently, longer strings of text (e.g. file path names) can extend outside the designated borders.

1) Open autoEdit 2 app
2) Add file to have access to transcript
3) Open transcript show page
4) Observe `info` button under video
5) Click info to reveal dropdown
6) Note text can extend past borders

<img width="238" alt="screenshot 2016-12-09 12 26 28" src="https://cloud.githubusercontent.com/assets/5640831/21058273/2aad7ccc-be0b-11e6-97a6-cc9289eebe82.png">

**Comment by pietrop** [comment]
temporary solved this by adding ` style="word-wrap:break-word;"` to [`lib/app/templates/transcription_show.html.ejs`](https://github.com/OpenNewsLabs/autoEdit_2/blob/master/lib/app/templates/transcription_show.html.ejs#L383) to wrap the words in the `well` that contains the metadata info.

```ejs
<div class="collapse" id="collapseMetadata">
 <div class="well"  style="word-wrap:break-word;">
...
```
![wrod_wrapped](https://cloud.githubusercontent.com/assets/4661975/21155100/c510e700-c13e-11e6-9a7e-1fcb77e908fc.png)

Fixed for version `1.0.6`.
