### ISSUE TITLE
No option to stop or delete after starting transcription

### ISSUE THREAD

**Issue by raj6996** [OpenNewsLabs/autoEdit_2#75]
I used pocketsphinx, no option to stop or delete files. Once I started it locked, any way to fix it.
**Desktop (please complete the following information):**
 - OS: PC
 - Version of your operating system Win10 Pro
 - Version of autoEdit Latest

**Comment by pietrop** [comment]
For now Pocketsphinx only works on Mac, I should hide the option on PC and Linux, to avoid confusion.

re stop or delete failed transcriptions, see these two issues https://github.com/OpenNewsLabs/autoEdit_2/issues/72 https://github.com/OpenNewsLabs/autoEdit_2/issues/42 .

Closing this unless you have follow up questions.
