### ISSUE TITLE
SRT/VTT Add option without Transcriptions

### ISSUE THREAD

**Issue by raj6996** [OpenNewsLabs/autoEdit_2#76]
Thanks for making awesome standalone tool as well as premiere pro extension, 
Is there anyway to add .srt, .vtt files (from youtube, video) without making transcription. It will help to edit fast.

**Comment by pietrop** [comment]
In the latest version `1.0.16` you can import `srt`captions, see screenshot. 
You select the audio /video file and the corresponding captions, srt, file. 
The srt file is then converted by autoEdit into a word accurate transcription. etc..

![screen shot 2018-10-13 at 20 14 42](https://user-images.githubusercontent.com/4661975/46909077-a5121c80-cf24-11e8-9f57-ca2ccc4cbc76.png)

Adding support for `vtt` would be possible and trivial, but is not implemented yet.

However re-youtube vtt, there's another mini-app I worked on to get captions from youtube, [`electron-video-downloader`](https://github.com/pietrop/electron-video-downloader), and the issue I had there is that in the recent version of YouTube vtt the lines repeat themselves a bit to achieve the karaoke effect on screen, which means when parsing a youtube vtt this should be consolidated.

For clarity, here is a regular vtt example

```
WEBVTT
Kind: captions
Language: en

00:00:00.000 --> 00:00:02.700
[Joseph Polizzotto] This
captioning workflow consists of

00:00:02.700 --> 00:00:04.200
four steps.

00:00:04.200 --> 00:00:08.800
Step 1: Generating a "raw
transcript" using YouTube's

...
```

This is a web vtt from youtube

```
WEBVTT
Kind: captions
Language: en
Style:
::cue(c.colorCCCCCC) { color: rgb(204,204,204);
 }
::cue(c.colorE5E5E5) { color: rgb(229,229,229);
 }
##

00:00:02.600 --> 00:00:05.440 align:start position:0%
 
my<00:00:03.409><c> name</c><00:00:03.560><c> is</c><00:00:03.710><c> Meredith</c><00:00:04.010><c> Broussard</c><c.colorCCCCCC><00:00:04.580><c> I</c><00:00:04.850><c> am</c><00:00:05.270><c> a</c></c>

00:00:05.440 --> 00:00:05.450 align:start position:0%
my name is Meredith Broussard<c.colorCCCCCC> I am a
 </c>

00:00:05.450 --> 00:00:07.420 align:start position:0%
my name is Meredith Broussard<c.colorCCCCCC> I am a
data<00:00:05.930><c> and</c><00:00:06.290><c> computational</c><00:00:06.920><c> journalism</c></c>

00:00:07.420 --> 00:00:07.430 align:start position:0%
data and computational journalism

....
```

As you can see it has word level timecodes and repeated words/sentences to achieve "karaoke effect" on playback.

Closing and marking this as question for now, but feel free to ask any follow up questions if needed.
