### ISSUE TITLE
No error message when uploading unsupported file types

### ISSUE THREAD

**Issue by SteveLeon2** [OpenNewsLabs/autoEdit_2#8]
The autoEdit app currently allows unsupported file types to be uploaded without displaying an error message. This results in a continuous loading wheel and the file cannot be deleted.

1) Open autoedit app from applications or dock
2) Click New
3) Click Choose File
4) Upload unsupported file (CSV or doc)
5) View app attempting to load file displaying no error message
6) View continuous loading wheel

![mac chrome elcap_autoedit2a](https://cloud.githubusercontent.com/assets/23086118/21060164/0660b5b0-be14-11e6-9e0b-6fcce23ca9f8.gif)

**Comment by pietrop** [comment]
Added a [filetype check](https://github.com/OpenNewsLabs/autoEdit_2/blob/master/electron/index.html#L153) for [ffmpeg supported file types](https://github.com/pietrop/ffmpeg_formats_list). 
 [_It has got some minor issue with having a comprehensive list_](https://github.com/pietrop/ffmpeg_formats_list/issues/3) but it's a good first pass. 

Closing this issue for now.
