### ISSUE TITLE
Typo on export menu modal

### ISSUE THREAD

**Issue by nanseay** [OpenNewsLabs/autoEdit_2#9]
On the Transcript Show page a user can export the transcription by clicking the "Export" button. 
In the Export menu modal, one of the options has a typo.

1) Open autoEdit 2 app
2) Add file to have access to transcript or open an existing transcript
3) On transcript show page, click Export button
4) On Export menu modal, scroll to `Plain Text Selections`

Expected: `Plain` Text EDL Chronological
Actual: `Palin` Text EDL Chronological
<img width="800" alt="typo on export modal" src="https://cloud.githubusercontent.com/assets/11615553/21060725/dd8470e8-be16-11e6-8f82-eb63e4cf5877.png">

**Comment by pietrop** [comment]
I've fixed it for version `1.0.6`.
