### ISSUE TITLE
i want to contribute with translation to spanish UI

### ISSUE THREAD

**Issue by johnfelipe** [OpenNewsLabs/autoEdit_2#99]
i want to contribute spanish translation strings if u can. Only share me strings and i will translate for u

**Comment by pietrop** [comment]
at the moment there is no setup to support translating the UI. autoEdit2 is largely in support mode, and more active development is in autoEdit3. We could look into adding that type of support to autoEdit3, but not very high on the priority list at the moment. 

But yeah if you want to look into this, you can raise In that case  and issue in this repo [github.com/pietrop/digital-paper-edit-client](https://github.com/pietrop/digital-paper-edit-client) (the front end for autoEdit3)
